version: 0.1
phases:
  install:
    commands:
      - npm install time
      - npm install
      - node run_zip
      - aws s3 cp awsconfig.zip s3://sgas.sam.aws-services-awsconfig
      - aws cloudformation package
         --template-file template.basic.yaml
         --s3-bucket sgas.sam.aws-services-awsconfig
         --output-template-file samTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
